In [2]:
from Baselines.trajopt import TrajOpt
from pybullet_environment import RobotEnvironment
import numpy as np

In [8]:
env = RobotEnvironment(gui = False)
trajopt = TrajOpt(env, num_joints = 7, traj_len = 128)

argv[0]=


In [9]:
start_joints = np.array([-1.9300085,  1.3141115,  2.1577177, -1.5229155, -0.7427585, 1.4192199, -1.3984755])
goal_pose = np.array([0.5,  0.01,  0.4, 0.1, 0, 0, 0.0008])

In [10]:
theta = start_joints.copy()
grad_theta = np.zeros((7,))

goal_pose = np.array([0.5,  0.01,  0.4, 0.1, 0, 0, 0.0008])
goal_transform = env.pose_to_transformation(goal_pose)

new_theta = theta + grad_theta

current_transform = env.forward_kinematics(new_theta)

print(current_transform)

[[-0.56982558  0.68723113  0.45056873  0.41445758]
 [ 0.81439932  0.39901596  0.42135497 -0.37570298]
 [ 0.10978414  0.60704171 -0.78705007  0.55888085]
 [ 0.          0.          0.          1.        ]]


In [4]:
trajopt.solve(start_joints, goal_pose)

((-0.005794493116621174, 0.005794493116621174), (-0.003525565089028546, 0.003525565089028546), (-0.005794493116621174, 0.005794493116621174), (-0.0030019663134302466, 0.0030019663134302466), (-0.005794493116621174, 0.005794493116621174), (-0.0037699111843077517, 0.0037699111843077517), (-0.005794493116621174, 0.005794493116621174), (-0.005794493116621174, 0.005794493116621174), (-0.003525565089028546, 0.003525565089028546), (-0.005794493116621174, 0.005794493116621174), (-0.0030019663134302466, 0.0030019663134302466), (-0.005794493116621174, 0.005794493116621174), (-0.0037699111843077517, 0.0037699111843077517), (-0.005794493116621174, 0.005794493116621174), (-0.005794493116621174, 0.005794493116621174), (-0.003525565089028546, 0.003525565089028546), (-0.005794493116621174, 0.005794493116621174), (-0.0030019663134302466, 0.0030019663134302466), (-0.005794493116621174, 0.005794493116621174), (-0.0037699111843077517, 0.0037699111843077517), (-0.005794493116621174, 0.005794493116621174), 

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [6]:
print(env.forward_kinematics(trajopt.theta[-trajopt.num_joints:]))
print(env.pose_to_transformation(goal_pose))

[[-0.2739408   0.88812589 -0.36903772  0.19877485]
 [ 0.5866396   0.45837065  0.66764536  0.19679914]
 [ 0.76210919 -0.03359683 -0.64657624  0.8945282 ]
 [ 0.          0.          0.          1.        ]]
[[ 1.          0.          0.          0.5       ]
 [ 0.         -0.99987201 -0.01599898  0.01      ]
 [ 0.          0.01599898 -0.99987201  0.4       ]
 [ 0.          0.          0.          1.        ]]


In [21]:
A = np.array([1, 2])
A = np.repeat([A], 3, axis = 0).flatten()
bounds = tuple([(-A[i], A[i]) for i in range(A.size)])

print(A)

[1 2 1 2 1 2]


In [11]:
import numpy as np
from scipy.optimize import minimize

# Example objective function (Rosenbrock function)
def rosenbrock(x):
    return sum(100.0 * (x[:, 1:] - x[:, :-1]**2)**2 + (1 - x[:, :-1])**2)

# Main optimization function
def main_optimization():
    # Define the initial guess x0 with shape (3, 4)
    x0 = np.zeros((3, 4))

    # Perform optimization using the minimize function
    result = minimize(fun=rosenbrock,
                      x0=x0,
                      method='SLSQP')

    return result

# Example usage
result = main_optimization()

# Print the result
print("Optimal solution:")
print(result.x)
print("Optimal function value:")
print(result.fun)


ValueError: 'x0' must only have one dimension.

## Start Joint Configuration:

#### From End-effector pose

In [3]:
start = np.array([0.5,  0.3,  0.2])
start_orientation = np.array([3.14, 0, 1.57])

joint_config = env.inverse_kinematics(start, start_orientation)
print(joint_config)

for i, joint_ind in enumerate(env.joints):
    env.client_id.resetJointState(env.manipulator, joint_ind, joint_config[i])

(0.5295944018839492, 1.7078429357776748, -0.030811500746328113, 0.5722936008432751, 0.032876890574846454, 1.1134821847667495, -0.23722034050664934, 0.0, 0.0)


#### From Joint angles

In [17]:
joint_config = np.array([-1.9300085,  1.3141115,  2.1577177, -1.5229155, -0.7427585, 1.4192199, -1.3984755])

for i, joint_ind in enumerate(env.joints):
    env.client_id.resetJointState(env.manipulator, joint_ind, joint_config[i])

## End Joint Configuration:

#### From End-effector pose

In [18]:
goal = np.array([0.5,  0.01,  0.4])
goal_orientation = np.array([3.14, 0, 0])

joint_config = env.inverse_kinematics(goal, goal_orientation)
print(joint_config)

for i, joint_ind in enumerate(env.joints):
    env.client_id.resetJointState(env.manipulator, joint_ind, joint_config[i])

(-1.7507875304579943, 0.5096944513152204, 1.9895427246792796, -1.9969491898086655, -0.4699207775449458, 1.7452850344385509, 1.1668836221913388, 0.0, 0.0)


#### From Joint angles

In [15]:
joint_config = np.zeros((9,))

for i, joint_ind in enumerate(env.joints):
    env.client_id.resetJointState(env.manipulator, joint_ind, joint_config[i])

# -------------------------------------------------------------------------------

In [22]:
env.client_id.disconnect()

numActiveThreads = 0
stopping threads
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed
finished
numActiveThreads = 0
btShutDownExampleBrowser stopping threads
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed
